# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
    displayName: 'Install system packages'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install PyQt5
      python -m pip install -r requirements.txt
      python -m pip install pytest pytest-azurepipelines pytest-faulthandler pytest-qt pytest-xvfb
    displayName: 'Install dependencies'
  - script: python setup.py develop
    displayName: 'Install MNELAB'
  - script: pytest -s mnelab/tests
    displayName: 'Run tests'

- job: 'macOS'
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install PyQt5
      python -m pip install -r requirements.txt
      python -m pip install pytest pytest-azurepipelines pytest-faulthandler pytest-qt
    displayName: 'Install dependencies'
  - script: python setup.py develop
    displayName: 'Install MNELAB'
  - script: pytest -s mnelab/tests
    displayName: 'Run tests'

- job: 'Windows'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install PyQt5
      python -m pip install -r requirements.txt
      python -m pip install pytest pytest-azurepipelines pytest-faulthandler pytest-qt
    displayName: 'Install dependencies'
  - script: python setup.py develop
    displayName: 'Install MNELAB'
  - script: pytest -s mnelab/tests
    displayName: 'Run tests'

- job: 'Oldest'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
    displayName: 'Install system packages'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
    displayName: 'Use Python 3.6'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install PyQt5==5.10.0
      awk '{gsub(/>=/, "==")}1' requirements.txt | awk '$0="\x27"$0"\x27"' | xargs python -m pip install
      python -m pip install pytest pytest-azurepipelines pytest-faulthandler pytest-qt pytest-xvfb
    displayName: 'Install dependencies'
  - script: python setup.py develop
    displayName: 'Install MNELAB'
  - script: pytest -s mnelab/tests
    displayName: 'Run tests'

- job: 'Optional'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
    displayName: 'Install system packages'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install PySide2
      python -m pip install -r requirements.txt
      python -m pip install -r requirements-extras.txt
      python -m pip install pytest pytest-azurepipelines pytest-faulthandler pytest-qt pytest-xvfb
    displayName: 'Install dependencies'
  - script: python setup.py develop
    displayName: 'Install MNELAB'
  - script: pytest -s mnelab/tests
    displayName: 'Run tests'

- job: 'Style'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
    displayName: 'Use Python 3.9'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install flake8
    displayName: 'Install dependencies'
  - script: flake8 .
    displayName: 'Run Flake8'
