# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- template: azure-template.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'

- template: azure-template.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.14'

- template: azure-template.yml
  parameters:
    name: Windows
    vmImage: 'windows-2019'
