

on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11.0, windows-2019]
        python-version: [3.6, 3.7, 3.8, 3.9]
        extras: [extras]
        packages: [latest]
        include:
          - os: ubuntu-20.04
            python-version: 3.9
            extras: no-extras
            packages: latest
          - os: ubuntu-16.04
            python-version: 3.6
            extras: extras
            packages: oldest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Linux dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
                         libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
                         libxcb-xinerama0 libxcb-xfixes0
    - name: Install latest dependencies
      if: ${{ matrix.packages == 'latest' }}
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: Install oldest dependencies
      if: ${{ matrix.packages == 'oldest' }}
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.10.0
        awk '{gsub(/>=/, "==")}1' requirements.txt | awk '$0="\x27"$0"\x27"' |\
        xargs python -m pip install
        pip install -r requirements-dev.txt
        pip install -e .
    - name: Install extra dependencies
      if: ${{ matrix.extras == 'extras' }}
      run: pip install -r requirements-extras.txt
    - name: Test
      run: pytest
